### ISSUE TITLE
ng2-dragula doesn't work with webpack

### ISSUE THREAD

**Issue by rogermeritt** [valor-software/ng2-dragula#8]
I have successfully managed to import this in to my project, and it doesn't give any compile errors, however once you browse to the page the console shows several exceptions and the page crashes.

![image](https://cloud.githubusercontent.com/assets/16588110/12163303/9257a870-b560-11e5-9a1b-addb63c33517.png)

It appears this stems from the fact that this component attempts to work with the window property, which is not available to the scope of packaged angular products built through things like webpack.

--------------------------------------------------------------------------------------
EXCEPTION: TypeError: window.dragula is not a function in [first-bag in Home@2:47]
vendor.bundle.js:25169 EXCEPTION: TypeError: window.dragula is not a function in [first-bag in Home@2:47]BrowserDomAdapter.logError @ vendor.bundle.js:25169
vendor.bundle.js:25169 ORIGINAL EXCEPTION: TypeError: window.dragula is not a functionBrowserDomAdapter.logError @ vendor.bundle.js:25169
vendor.bundle.js:25169 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ vendor.bundle.js:25169
vendor.bundle.js:25169 TypeError: window.dragula is not a function
    at Dragula.ngOnInit (http://localhost:3000/main.bundle.js:272:44)
    at

**Comment by SKMan** [comment]
same here

**Comment by SKMan** [comment]
figured! Include original dragula.min.js first

**Comment by SKMan** [comment]
figured! Original dragula.js should be included.

**Comment by valorkin** [comment]
Yes, it is. Ng2-dragula is just a ng2 wrapper for original dragula

**Comment by rogermeritt** [comment]
Sorry i dont understand, what is the fix? What do i need to include?  You can't just include a js file in index.html it is not accessible by the webpack vars.

**Comment by SKMan** [comment]
The js file from https://github.com/bevacqua/dragula. As valorkin said ng2-dragula is a wrapper for the original js of dragula. As you said, just include it in a script tag in index.html like you do other libs; such as system.js.

**Comment by valorkin** [comment]
or you can `require` original dragula

**Comment by rigoleto** [comment]
I'd like to elevate this issue again, since I think accessing dragula through `window` is a problem for all javascript bundlers. I'm encountering it using Browserify currently. Requiring dragula isn't going to work - it doesn't assign `window.dragula`. I'm currently trying to find a way to manually work around this.

**Comment by nanomo** [comment]
sorry for the noob question, im having the same issue, so i donwloaded https://github.com/bevacqua/dragula/blob/master/dragula.js and tried to include in my index.html but im having this error: 

> 
> Uncaught ReferenceError: require is not defined(anonymous function) @ dragula.js:3
> vendor.bundle.js:7954 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

Im using webpack server with this setup:
webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 8080 --content-base src

**Comment by valorkin** [comment]
according to this https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L1
dragula is UMD compatible

catch is you can not `require` dragula from component directly
or maybe can
if using UMD style require, write something like UMD style require polifyll
need to think about it and maybe find one

**Comment by rigoleto** [comment]
dragula is compatible with module loaders, ng2-dragula is not, since instead of importing/requiring dragula, it uses window.dragula.

**Comment by valorkin** [comment]
@NathanWalker please check this issue, I suppose it could be fixed pretty fast

**Comment by NathanWalker** [comment]
Definitely. I'll fix this tonight.

**Comment by NathanWalker** [comment]
@rogermeritt @rigoleto just released `1.0.2`... which should solve this issue for you.
Please let me know if you still have trouble and reopen if so. Thanks.

**Comment by rigoleto** [comment]
This is still an issue for me, that I don't think will be resolved until the lib explicitly imports dragula. In the meantime, I'm working around it by bundling in dragula, but also adding the following:

```html
<script type="text/javascript">
      window.dragula = require('dragula');
</script>
```

**Comment by valorkin** [comment]
Try latest beta version

**Comment by NathanWalker** [comment]
I'm fixing this right now :+1:

**Comment by rigoleto** [comment]
This is working exactly as expected now - thanks for your work!
